DOCKMON/config/routes.rb
Rails.application.routes.draw do
  get 'live_container/read_container_file'
  get 'live_container/documentation'
  get 'live_container/show_details'
  get 'live_container/terminal_action'

  root 'live_container#index'

end

DOCKMON/app/models/net_detail.rb
class NetDetail < ActiveRecord::Base
end

DOCKMON/app/models/netdetail.rb
class Netdetail < ActiveRecord::Base
	self.table_name = "netdetails"
end

DOCKMON/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

DOCKMON/app/controllers/live_container_controller.rb
# Licensed by GPL/GNU 2016 DOCKMON version 0.1 
# This File is considered as Main Controller of the Application
# Developed By: Nikit Swaraj DevOps Foradian Tech. 2016

class LiveContainerController < ApplicationController
  def index
  end

  def read_container_file
  @netdetail = Netdetail.all
  end
 
  def documentation
  end

  def show_details
   @netdetails = Netdetail.find_by(:Cont_name => params[:Cont_name])
   respond_to do |format|
   format.js {}
  end
  end

  def terminal_action
   @netdetails = Netdetail.find_by(:Cont_name => params[:Cont_name])
   `xterm -geometry 120*24+400+1500 -T DOCKMON -e docker stats nikit`
  
  end


end

DOCKMON/app/helpers/application_helper.rb
module ApplicationHelper
end

DOCKMON/app/helpers/live_container_helper.rb
module LiveContainerHelper
end

DOCKMON/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DOCKMON</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>



</body>
</html>


<style>
#container_modal{
	top: 0px;
	position: absolute;
	width: 100%;
}
</style>

DOCKMON/app/views/live_container/_show_details.html.erb
<!-- Modal -->
    <div class="modal-dialog" style="margin-top: 100px; width: 70%;" >
   
      <!--modal Modal content-->
      <div class="modal-content">
        <div class="modal-header" style="background-color: #22B8EB; color: white;">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title"><%= @netdetails.Cont_name %></h4>


          

           <!-- <button type="button" class="btn btn-default" data-dismiss="modal" style="background-color: #7FFF00;color: black; margin-left: 850px;">Dynamic Data</button> -->



        </div>
        <div class="modal-body">
    		<table class="table-bordered" style="margin: 0 auto;">
			<tbody>
				<tr>
					<th>Image ID</th>
					<td><%= @netdetails.ImageID %></td>
				</tr>
				<tr>
					<th>Image NO</th>
					<td><%= @netdetails.ImageNO %></td>
				</tr>
				<tr>
					<th>State Process ID</th>
					<td><%= @netdetails.State_Pid %></td>
				</tr>
				<tr>
					<th>Created On</th>
					<td><%= @netdetails.DATE %></td>
				</tr>
				<tr>
					<th>Container Name</th>
					<td><%= @netdetails.Cont_name %></td>
				</tr>		
				<tr>
					<th>Process Running</th>
					<td><%= @netdetails.command %></td>
				</tr>
				<tr>
					<th>Operating System</th>
					<td><%= @netdetails.os %></td>
				</tr>
				<tr>
					<th>Container Status</th>
					<td><%= @netdetails.Status %></td>
				</tr>
				<tr>
					<th>Memory</th>
					<td><%= @netdetails.Memory %></td>
				</tr>
				<tr>
					<th>Swap Memory</th>
					<td><%= @netdetails.Swap_mem %></td>
				</tr>
				<tr>
					<th>Kernel Memory</th>
					<td><%= @netdetails.Kernel_mem %></td>
				</tr>
				<tr>
					<th>CPU Cores</th>
					<td><%= @netdetails.CPU_core %></td>
				</tr>
				<tr>
					<th>CPU Qoutas</th>
					<td><%= @netdetails.CPU_Qouta %></td>
				</tr>
				<tr>
					<th>IPv4</th>
					<td><%= @netdetails.IPv4 %></td>
				</tr>
				<tr>
					<th>Gateway</th>
					<td><%= @netdetails.Gateway %></td>
				</tr>
				<tr>
					<th>Mac Address</th>
					<td><%= @netdetails.MacADD %></td>
				</tr>

			</tbody>
			</table>
        </div>
        <div class="modal-footer">
        <div>
          <%= link_to live_container_terminal_action_path(:Cont_name => @netdetails.Cont_name),:class => " btn btn-info btn-sm" do %>
          Dynamic Data
          <%end%>
          <button type="button" class="btn btn-danger btn-sm" data-dismiss="modal">Close</button>
         </div>
        </div>
      </div>
      
    </div>
<style type="text/css">
	th,td{
		padding: 1px 20px;
	}
</style>

DOCKMON/app/views/live_container/index.html.erb
  <div class="container-fluid header">
    <div class="pull-left">
     <h1 class="dockmon-title" style="font-size:48px;"><span style="text-decoration:underline;">Dock</span><span style="border: 2px solid #22B8EB; padding: 1px 10px; margin-left:2px;">Mon</span></h1>
    </div>
    <div class="pull-right about-devop">
      <a href="/live_container/documentation" style="color:#22B8EB">Documentation</a> |
      <a href="" style="color:#22B8EB">About</a>
    </div>
  </div>
  <div class="container-fluid welcome-page">
    <h1 class="docker-monitoring" style="text-align:center;"><B>Monitoring System</B></h1>
    <br><br>
    <%= link_to("Start Monitoring",{:controller => 'live_container', :action => 'read_container_file'}, :class => "start-monitoring") %>
  </div>
  

<style type="text/css">
  
  
 body {
    background-image: url(<%= asset_path 'docker-facebook.png'%>);
    background-size: cover;
    background-repeat: no-repeat;
      }

  
</style>

DOCKMON/app/views/live_container/read_container_file.html.erb
<div class="container-fluid header">
    <div class="" Style="text-align:center">
      <h1 class="dockmon-title" style="font-size:48px;"><span style="text-decoration:underline;">Dock</span><span style="border: 2px solid #22B8EB; padding: 1px 10px; margin-left:2px;">Mon</span></h1>
    </div>
</div>

<h2 style="text-align:center; color:white;">Following are the running containers</h2>

<h5 style="font-family: Arial; color: #fff;text-align:center"><i> Host Machnine: <%=`ifconfig eth0 | grep inet`%> </i></h3>
<h5 style="font-family: Arial; color: #fff;text-align:center">FQDN: <%= `hostname`.strip%></h5>
<h5 style="font-family: Arial; color: #fff;text-align:center"><b> Total No of running Containers: <%= @netdetail.count%></b></h5>
<div class= "container docker-container">
	<% @netdetail.each do |nd| %>
		<div class="col-md-4">
 			<!-- <a class="btn btn-alert maincontent animated zoomIn " style="border-radius:100%; margin-top:75px; margin-left:125px;"> -->
 			<%= link_to live_container_show_details_path(:Cont_name => nd.Cont_name),:data => {:remote => true, "target" => "#container_modal"}, :class => "btn btn-alert maincontent animated zoomIn" do %><%= nd.Cont_name %><%end%>
 		</div>
	<% end %>
 </div>
 <div id="container_modal"></div>

<div>
<div>
	
</div>
<style type="text/css">

body {
	/*background-color: grey;*/
	background-image: url(<%= asset_path 'blue.jpg'%>);*/
}

.maincontent {
	border-radius:100%; margin-top:75px; margin-left:125px;
}
</style>

DOCKMON/app/views/live_container/show_details.js.erb
$("#container_modal").html("<%= escape_javascript(render 'show_details')%>")
$("#container_modal").modal({
		'backdrop': false,
		'show': true,
		'keyboard': false,
		'top': '0px',
		'width': 'auto'
	});